jenkinsci/jenkins-charm

tox.ini
The latest charm-test release has been fixed so it doesn't require the custom fixtures fork from my repository anymore.
=> Bump charm-test required version to fix unit tests

lib/charms/layer/jenkins/api.py, unit_tests/fakes.py, unit_tests/test_api.py
This fixes #14, a regression highlighted by the slave integration tests,
where starting from Jenkins 2.27 the slave would be rejected at
registration.
See also:
https://issues.jenkins-ci.org/browse/JENKINS-39232
=> Configure new nodes to use the JNLP launchers

config.yaml, lib/charms/layer/jenkins/api.py, lib/charms/layer/jenkins/configuration.py, lib/charms/layer/jenkins/paths.py, lib/charms/layer/jenkins/service.py, reactive/jenkins.py, templates/location-config.xml, tests/basic.py, unit_tests/states.py, unit_tests/test_api.py, unit_tests/test_configuration.py, unit_tests/test_service.py, unit_tests/test_users.py
This change adds the public_url charm configuration option so you can
specify the Jenkins URL and prefix.
=> Add configuration for setting the Jenkins URL.

README.md, TODO.md, lib/charms/layer/jenkins/storage.py, metadata.yaml, reactive/jenkins.py, tests/02-xenial-website, tests/basic.py, tests/deployment.py, unit_tests/test_storage.py
The latest committed version of amulet and juju-deployer are needed for storage support in the tests.
=> Add storage support.

lib/charms/layer/jenkins/configuration.py, templates/location-config.xml, unit_tests/test_configuration.py
the remaining XML node <jenkinsUrl></jenkinsUrl> causes a JNLP invalid argument error
Signed-off-by: Eric Villard <dev@eviweb.fr>
=> fix #28 slave connection issue due to empty url

README.md, config.yaml, lib/charms/layer/jenkins/configuration.py, reactive/jenkins.py, templates/jenkins-config.xml, unit_tests/test_configuration.py
Currently Jenkins defaults to setting up slaves to communicate on a random port.
If slaves are deployed behind default-deny firewalls, the administrator will have no way to know which port must be opened to grant access.
This PR changes that behaviour to use a specific, configurable port instead (48484 by default).
=> Use a specific (configurable) port for slave JNLP connections

lib/charms/layer/jenkins/credentials.py, lib/charms/layer/jenkins/plugins.py, lib/charms/layer/jenkins/users.py, reactive/jenkins.py, unit_tests/test_credentials.py, unit_tests/test_plugins.py
This change improves error handling and fixes a few bug I hit during testing
* improve password handling to avoid relying on config variables which sometimes disappear
* improve plugin installation error handling
* replace unreliable @only_once decorator with @when_not
=> A few error handling fixes

.gitignore, lib/charms/layer/jenkins/api.py, unit_tests/fakes.py, unit_tests/test_api.py, wheelhouse.txt
python-jenkins uses requests as of version 0.4.16.  The previous build of the charm shipped 0.4.15, and fresh builds are shipping 1.4.0.
This branch updates the charm's Jenkins API code to use the correct type of Request object and to retry correctly during Jenkins startup by catching the requests-flavoured exceptions.
=> convert our Jenkins API code to work properly with requests

reactive/jenkins.py
Mainly intended for the release=bundle case, but upgrade-charm is a good hint
that we should upgrade everything possible.
I originally tried gating on get_state("apt.installed.jenkins") but it returned None,
which was pretty surprising to me. Oh well, if the package isn't installed it should be,
so we can probably live without the check.
=> upgrade_jenkins: new function triggered by upgrade-charm

lib/charms/layer/jenkins/api.py, lib/charms/layer/jenkins/packages.py, lib/charms/layer/jenkins/users.py, requirements.txt, unit_tests/stubs/apt.py, unit_tests/test_api.py, unit_tests/test_packages.py, unit_tests/test_users.py
Addresses https://github.com/jenkinsci/jenkins-charm/issues/47
=> use new-style API tokens for Jenkins >= 2.129.1

reactive/jenkins.py
Adjusts configure_plugins to run when any of plugin configs have been changed, but only if the admin configuration flag is already present.
And fix a bug where the charm would get stuck in maintenance after installing plugins.
=> Fix bugs introduced by auto-update plugins

config.yaml, lib/charms/layer/jenkins/api.py, lib/charms/layer/jenkins/plugins.py, reactive/jenkins.py, requirements.txt, unit_tests/test_api.py, unit_tests/test_plugins.py, wheelhouse.txt
This PR makes the plugin installation take care of plugin dependencies. It also uses the jenkins-plugin-manager module to download, install and update plugins, instead of the old method of using wget.
It also removes the force-reinstall charm config as it becomes redundant with the newer update method.
Additionally it closes #66
=> Plugin dependencies

actions/upgrade, config.yaml, lib/charms/layer/jenkins/api.py, lib/charms/layer/jenkins/packages.py, reactive/jenkins.py, unit_tests/test_api.py, unit_tests/test_packages.py
This MP adds a new way of upgrading jenkins package. It adds a new configuration `bundle-site` that sets an archive to download the package from if there's a newer version available.
There's also a new action to run the upgrade.
=> Upgrade package from bundle-site

layer.yaml, lib/charms/layer/jenkins/packages.py, metadata.yaml
This has been tested on bionic and focal with charm-helpers 0.20.10, and I've confirmed net-tools is available in xenial.
=> Add focal support

lib/charms/layer/jenkins/plugins.py
By default, UpdateCenter will download plugins to a file like
./foo-x.y.jpi, which jenkins will unpack to a directory called ./foo-x.y.
For some versions of jenkins, this causes Jenkins to ignore it in favour
of its built in plugins, which it will install into ./foo.  This change means that
downloaded plugins will not have the version suffix, and thus be respected by jenkins properly.
=> Set with_version=False for plugin download.

lib/charms/layer/jenkins/packages.py
This PR fix an issue where setting the bundle-site to https://pkg.jenkins.io will crash the charm when trying to download the jenkins package. That occurs because the official latestCore.txt file lives in https://updates.jenkins.io/stable/latestCore.txt.
When using a custom bundle-site, the charm expects that file to be under the same domain. This can't be expected from the official repository.
=> Use JenkinsCore defaults when downloading deb from pkg.jenkins.io

layer.yaml
Charm source URL in layer.yaml is incorrect, and causing confusion. Fix it.
=> Correct charm source repo URL

wheelhouse.txt
wheelhouse.txt has an invalid entry, causing 'charm build' to explode.
=> Fix invalid entry in wheelhouse.txt

wheelhouse.txt
Using "-e" is not recommended for production usage.
Also, git+https avoid git/ssh settings.
=> Remove editable flag and use git+https

lib/charms/layer/jenkins/plugins.py
We had a situation where we ended with:
```
drwxr-xr-x  75 root    root    12288 Dec 11 03:57 plugins
drwxr-xr-x 138 jenkins nogroup 12288 Jul  1 09:50 plugins.old
drwxr-xr-x  75 root    root    12288 Dec 11 10:52 plugins_charm_backup
```
The logs in the unit suggest that something happened
```
2020-12-11 03:57:44 INFO juju-log Invoking reactive handler: reactive/jenkins.py:192:update_plugins
2020-12-11 03:57:44 INFO juju-log status-set: maintenance: Updating plugins
2020-12-11 03:57:45 INFO juju-log Backing up plugins.
2020-12-11 03:57:56 INFO juju-log Updating plugins
2020-12-11 03:57:56 INFO juju-log Installing plugins (junit jsch plain-credentials run-condition git-client workflow-basic-steps scm-api rebuild build-pipeline-plugin maven-plugin credentials-binding build-blocker-plugin …
```
=> Plugin ownership

config.yaml, metadata.yaml, unit_tests/test_credentials.py, unit_tests/test_users.py
Set default password to reduce simple case deployment steps, and update maintainer
=> Set default password to reduce simple case deployment steps, and update maintainer

metadata.yaml
Add a link to discourse-based documentation for display on https://charmhub.io/jenkins/docs.
=> Add a link to discourse-based documentation

lib/charms/layer/jenkins/plugins.py, unit_tests/test_plugins.py
Currently we only allow download of `.hpi` plugins, but in some cases a `.jpi` file is available instead. Allow downloads of either.
=> Allow downloads of .jpi and .hpi plugins

reactive/jenkins.py
This addresses https://github.com/jenkinsci/jenkins-charm/issues/111. Jenkins will be restored to its previous known good state, but Juju will report a blocked status, with a message such as `Cannot find plugin doesntexist`.
=> If we have an invalid plugin, report that and set status to blocked

lib/charms/layer/jenkins/plugins.py, unit_tests/test_plugins.py
Closes #117 
Instead, trust jenkins_plugin_manager UpdateCenter to use consult
uc_data to find a more correct plugin_url
Relevent issue: https://github.com/jenkinsci/jenkins-charm/issues/117
Summarising the issue, the way the charm determines the url to download plugins from is a little problematic. It makes assumptions which aren't always valid, and has lead to incorrect versions of plugins being downloaded (such as the credentials plugin as of writing).
So instead, I've delegated this task to `jenkins_plugin_manager`, which uses the `update-centre.json` provided by Jenkins to determine the correct url to download your plugin from (or at least, a url matching the version stated in the logs)
=> Stop using plugin-site to calc plugin-url

lib/charms/layer/jenkins/packages.py
It seems that jenkins has discontinued pkg.jenkins-ci.org as a mirror for pkg.jenkins.io and the charm is failing to install with:
```
unit-jenkins-3: 15:05:23 WARNING unit.jenkins/3.update-status E: Failed to fetch http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.346.1_all.deb  404  Not Found [IP: 52.202.51.185 80]
unit-jenkins-3: 15:05:23 WARNING unit.jenkins/3.update-status E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.263.4_all.deb returns 404 but its replacement works: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.346.1_all.deb
I've tested this change locally.
=> Set pkg.jenkins.io as APT_SOURCE

.gitignore, lib/charms/layer/jenkins/packages.py, lib/charms/layer/jenkins/users.py, metadata.yaml, pyproject.toml, reactive/jenkins.py, tests/integration/conftest.py, tests/integration/test_charm.py, tests/integration/types.py, tox.ini, unit_tests/test_packages.py, unit_tests/test_plugins.py
- Changes to install the default jre version for all Ubuntu series
- Migrate the basic integration tests to pytest operator
=> Support Jenkins 2.361 and migrate basic integration tests to pytest operator

tests/integration/test_charm_agent.py
A new version of Jenkins agent charm was released to fix support for Xenial.
The integration test with Jenkins agent charm on Xenial was disabled.
This pull request re-enable the integration test.
I have ran ` tox -e integration -- -k agent` and the test result was successful.
=> Enable integration test with Jenkins agent charm on Xenial.

README.md
Add badges:
- CharmHub Badge
- Integration Test
- Discourse Status
There are no workflows for Release to Edge and Promote charm so is not possible to add badges for them.
=> docs(ISD-454): Add badges

config.yaml, lib/charms/layer/jenkins/api.py, lib/charms/layer/jenkins/configuration.py, tests/integration/config.py, tests/integration/conftest.py, tests/integration/test_charm_website.py, unit_tests/test_api.py
This PR addresses issue #148 and adds the `no_proxy` configuration setting to the charm.
`juju deploy ./jenkins_ubuntu-16.04-amd64_ubuntu-18.04-amd64_ubuntu-20.04-amd64.charm --series focal --config proxy-hostname=localhost --config proxy-port=8080 --config proxy-username=helloworld --config proxy-password=helloworld --config no-proxy=abc.com,def.net,10.200.114.151,localhost`
`jenkins_ubuntu-16.04-amd64_ubuntu-18.04-amd64_ubuntu-20.04-amd64.charm` refers to the charm built with code in current PR.
```[tasklist]
```
=> feat: no-proxy configuration value
